### ISSUE TITLE
Where to find the resource map?

### ISSUE THREAD

**Issue by jrj-d** [nevalla/lens-resource-map-extension#2]
Hi,

Thanks for working on this extension, there's great potential here!
I was curious, wanted to check it out, and installed it in Lens. But I can't find the resource map anywhere in the interface.
Where can I find it?

Lens Version:
```
Lens: 4.1.4
Electron: 9.4.0
Chrome: 83.0.4103.122
Node: 12.14.1
Copyright 2020 Mirantis, Inc.
```

Extension version: 0.2.0
![image](https://user-images.githubusercontent.com/7548106/111025158-b821c300-83e2-11eb-921b-0c96fd913bfa.png)

I've restarted Lens several times to make sure there was no hidden state.

**Comment by Wagz123** [comment]
On my Lens install, the resource map shows up as an option on the explorer menu to the left after you select a cluster. 

![Capture](https://user-images.githubusercontent.com/58535810/111703019-0ed83400-880b-11eb-990e-0e8022c15435.PNG)

**Comment by jrj-d** [comment]
Thanks for your answer! I can't see it unfortunately.

**Comment by Wagz123** [comment]
Try uninstalling the extension, exiting lens, starting lens as run as administrator, then install the extension through a direct url to the tgz rather than downloading it first.  That's pretty much how I installed it, then I restarted lens as a regular user. It's worth giving  it a shot, the resource map is interactive and there  quite a bit of realtime manipulation you can do with it.  pretty cool.  Also, my lens install is installed as "only me" rather than anyone using the system.

**Comment by AlliotTech** [comment]
the resourceMap is empty... 
![image](https://user-images.githubusercontent.com/24980252/115646578-fcdf3900-a354-11eb-8f41-0c571af723eb.png)

**Comment by AlliotTech** [comment]
sorry . i forgot to list my environment:  
``` 
Lens: 4.2.2
Electron: 9.4.0
Chrome: 83.0.4103.122
Node: 12.14.1
macOS Big sur 
```

**Comment by nevalla** [comment]
Please re-open if this is still an issue.
